### ISSUE TITLE
[1.16.4] Mod fails to load with AdoptOpenJDK OpenJ9 11.0.9 in Enigmatica6

### ISSUE THREAD

**Issue by telemenar** [enemeez/simplefarming#134]
**Forge Version**
35.1.13

**Mod list (optional)**
Enigmatica6 0.3.2

**Log file (optional)**
```
-- MOD simplefarming --
Details:
	Mod File: simplefarming-1.16.4-1.3.5.jar
	Failure message: Simple Farming (simplefarming) has failed to load correctly
		java.lang.IllegalStateException: Failed to resolve consumer event type: enemeez.simplefarming.SideProxy$$Lambda$7730/000000000000000000@5c3df8ee
	Mod Version: 1.16.4-1.3.5
	Mod Issue URL: https://github.com/cweckerl/simplefarming/issues
	Exception message: java.lang.IllegalStateException: Failed to resolve consumer event type: enemeez.simplefarming.SideProxy$$Lambda$7730/000000000000000000@5c3df8ee
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.getEventClass(EventBus.java:220) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:226) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addGenericListener(EventBus.java:207) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addGenericListener(EventBus.java:202) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addGenericListener(EventBus.java:197) ~[eventbus-3.0.5-service.jar:?] {}
	at enemeez.simplefarming.SideProxy.<init>(SideProxy.java:43) ~[simplefarming:1.16.4-1.3.5] {re:classloading}
	at enemeez.simplefarming.SideProxy$Client.<init>(SideProxy.java:68) ~[simplefarming:1.16.4-1.3.5] {re:classloading}
	at enemeez.simplefarming.SimpleFarming.lambda$null$0(SimpleFarming.java:26) ~[simplefarming:1.16.4-1.3.5] {re:classloading}
	at enemeez.simplefarming.SimpleFarming$$Lambda$7295/000000000000000000.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[forge:?] {re:classloading}
	at enemeez.simplefarming.SimpleFarming.<init>(SimpleFarming.java:26) ~[simplefarming:1.16.4-1.3.5] {re:classloading}
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[?:?] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3247/000000000000000000.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3741/000000000000000000.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
```

**Describe the issue**
For now I'll just switch to another JRE but looks like something is subtly off with the biome generation registration.

The code that is triggering this is:
```
		eventBus.addGenericListener(Feature.class, ModWorldGen::registerAll);
		MinecraftForge.EVENT_BUS.addListener(EventPriority.HIGH, SimpleGeneration::onBiomeLoad);
```
https://github.com/cweckerl/simplefarming/blob/1.16/src/main/java/enemeez/simplefarming/SideProxy.java#L43

Not 100% sure why. Though Farmer's Delight has the same issue though out of the 240+ mods in Enigmatica 6 0.3.2

**Comment by telemenar** [comment]
Just learned that OpenJ9 is not a valid JVM for forge but newer versions of OpenJ9 are not caught. Closing as invalid.
